channels:
- conda-forge
dependencies:
- pybind11=2.11.1
- python=3.10
- numpy=1.26.0
- setuptools
- wheel
- pytest
- pytest-html
- mpi4py=3.1.5
- cython=0.29.36
- h5py
- pyyaml
- jupyterlab
- ipykernel
- jupyter_client
- gcc_linux-64  # Compilateur C
- gxx_linux-64  # Compilateur C++
