name: maia-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.0
  - pybind11=2.8.1
  - mpi4py=3.1.5
  - setuptools
  - wheel
  - pytest
  - pytest-html
  - cython=0.29.36
  - h5py
  - pyyaml
  - sphinx
  - sphinx-rtd-theme
  - sphinx-tabs
  - gxx_linux-64
