#!/bin/bash

set -e  # Stop on error

echo "Cloning Maia repository..."
git clone https://github.com/onera/Maia

cd Maia
git submodule update --init

echo "Building Maia..."

# Create build directory
mkdir -p build
cd build

# Define Python paths
PYTHON_EXEC=$(which python)
PYTHON_INCLUDE_DIR=$(${PYTHON_EXEC} -c "from sysconfig import get_paths as gp; print(gp()['include'])")
NUMPY_INCLUDE_DIR=$(${PYTHON_EXEC} -c "import numpy; print(numpy.get_include())")

# Run cmake
cmake ../ \
  -DCMAKE_INSTALL_PREFIX="$(pwd)/../Dist" \
  -DCMAKE_CXX_STANDARD=17 \
  -DCMAKE_EXE_LINKER_FLAGS='-lz -lbz2' \
  -DCMAKE_SHARED_LINKER_FLAGS='-lz -lbz2' \
  -DPDM_ENABLE_LONG_G_NUM=OFF \
  -DPDM_ENABLE_EXTENSION=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DPYTHON_EXECUTABLE="${PYTHON_EXEC}" \
  -DPython_INCLUDE_DIRS="${PYTHON_INCLUDE_DIR}" \
  -DPython_NumPy_INCLUDE_DIRS="${NUMPY_INCLUDE_DIR}" \
  -DPython_NumPy=ON

make 
make install

# Add to PYTHONPATH
echo "export PYTHONPATH=\$PYTHONPATH:$(pwd)/../Dist/lib" >> ~/.bashrc

# For current script session (even if notebook later will reread bashrc)
export PYTHONPATH="$PYTHONPATH:$(pwd)/../Dist/lib"

echo "Maia built and installed."
